#!/bin/bash

#
# Functional and unit tests for syz
#


if [ "$1" != real ]; then
	unset SYZ_{PATH,MODULES,MODULES_ABS,INACTIVE_MODULES}
	exec time bash --norc "$0" real "$@"
fi
shift # eat the "real"

for i; do
	case "$i" in
		-v)
			verbose=y
			;;
		-q)
			quiet=y
			;;
	esac
done
unset i

# Setup

basedir=""
trap '__syz_rc="$?" ; set +ex ; echo ; if [ $__syz_rc = 0 ]; then echo "ALL TESTS PASSED"; else echo "TEST FAILED ($__syz_rc)"; fi ; [ "$basedir" ] && rm -rf "$basedir" ; exit $__syz_rc' EXIT
basedir="${SYZZLE_TEST_BASEDIR:-$(mktemp -d)}"
if [ ! -e "$basedir" ]; then
	mkdir -p "$basedir"
fi
__syz_tmpfile="$basedir/tmpfile"

nl='
'
test_pvs=""
for i in {abc,def,ghi,jkl}/{1.0,1.1,1.2,1.3}; do
	test_pvs="$test_pvs$i$nl"
done
unset i
test_pvs="${test_pvs%$nl}"
#echo "$test_pvs"
export SYZ_PATH="$basedir/sw"

srcdir="${0%/*}"
testdir="$srcdir/test"

if [ ! -d "$srcdir" -o ! -r "$srcdir" ]; then
	echo "Unable to find/read $srcdir"
	exit 1
fi
if [ ! -d "$testdir" -o ! -r "$testdir" ]; then
	echo "Unable to find/read $testdir"
	exit 1
fi

. "$testdir"/lib || { echo "Unable to load $testdir/lib" ; exit 1; }

. "$testdir"/checks || { echo "Unable to load $testdir/checks" ; exit 1; }

. "$testdir"/tests || { echo "Unable to load $testdir/tests" ; exit 1; }

