#!/bin/bash

#
# Functional and unit tests for syz
#


if [ "$1" != real ]; then
	unset SYZ_{PATH,MODULES,MODULES_ABS,INACTIVE_MODULES}
	exec bash --norc "$0" real
fi

# Setup

basedir=""
trap 'rc="$?" ; set +ex ; echo ; if [ $rc = 0 ]; then echo "ALL TESTS PASSED"; else echo "TEST FAILED ($rc)"; fi ; [ "$basedir" ] && rm -rf "$basedir" ; exit $rc' EXIT
basedir="$(mktemp -d)"
tmpfile="$basedir/tmpfile"

nl='
'
test_pvs=""
for i in {abc,def,ghi,jkl}/{1.0,1.1,1.2,1.3}; do
	test_pvs="$test_pvs$i$nl"
done
test_pvs="${test_pvs%$nl}"
#echo "$test_pvs"
export SYZ_PATH="$basedir/sw"

marker="+"

function indent {
	marker="$marker+"
}

function unindent {
	marker="${marker%+}"
}

function run {
	indent
	echo "$marker ${FUNCNAME[0]} $*"
	"$@" > "$tmpfile"
	rc="$?"
	o="$(<"$tmpfile")"
	unindent
}

function via_tty {
	indent
	echo "$marker ${FUNCNAME[0]} $*"
	function tty {
		:
	}
	"$@"
	unset -f tty
	unindent
}


function check {
	local what="$1" ; shift
	indent
	set -e
	check_"$what" "$@"
	set +e
	unindent
}

function check_success {
	echo "$marker ${FUNCNAME[0]}"
	[ "$rc" = "0" ]
}

function check_failure {
	local code="$1" ; shift
	echo "$marker ${FUNCNAME[0]} $code"
	if [ "$code" ]; then
		[ "$rc" = "$code" ]
	else
		[ "$rc" != "0" ]
	fi
}

function check_output_pattern {
	local i
	for i; do
		echo "$marker ${FUNCNAME[0]} $i"
		grep -q "$i" <<<"$o"
	done
}

function check_output_not_pattern {
	local i
	for i; do
		echo "$marker ${FUNCNAME[0]} $i"
		! grep -q "$i" <<<"$o"
	done
}

function check_output_exact {
	local target="$1" ; shift
	echo "$marker ${FUNCNAME[0]}"
	[ "$o" = "$target" ]
}

function check_envvar_pattern {
	local var="$1" ; shift
	local pattern="$1" ; shift
	local -n value="$var"
	echo "$marker ${FUNCNAME[0]} $var $pattern"
	grep -q "$pattern" <<<"$value"
}

function check_envvar_not_pattern {
	local var="$1" ; shift
	local pattern="$1" ; shift
	local -n value="$var"
	echo "$marker ${FUNCNAME[0]} $var $pattern"
	! grep -q "$pattern" <<<"$value"
}

function check_envvar_exact {
	local var="$1" ; shift
	local target="$1" ; shift
	local -n value="$var"
	echo "$marker ${FUNCNAME[0]} $var"
	[ "$value" = "$target" ]
}

function check_envvar_set {
	local i
	for i; do
		echo "$marker ${FUNCNAME[0]} $i"
		[ "${!i+set}" = "set" ]
	done
}

function check_envvar_unset {
	local i
	for i; do
		echo "$marker ${FUNCNAME[0]} $i"
		[ "${!i+set}" != "set" ]
	done
}

function check_no_modules_loaded {
	echo "$marker ${FUNCNAME[0]}"
	run syz loaded
	check success
	check output_exact ""
	via_tty run syz loaded
	check success
	check output_pattern 'No modules currently loaded\.'
}

function check_no_modules_inactive {
	echo "$marker ${FUNCNAME[0]}"
	run syz inactive
	check success
	check output_exact ""
	via_tty run syz inactive
	check success
	check output_pattern 'No inactive modules\.'
}

function check_modules_loaded {
	local i
	for i; do
		echo "$marker ${FUNCNAME[0]} $i"
		run syz loaded
		check success
		check output_pattern "^$i$"
		via_tty run syz loaded
		check success
		check output_pattern 'Currently loaded modules'
		check output_pattern "\<$i\>"
		run syz isloaded "$i"
		check success
		check output_exact "$i loaded"
	done
}

function check_modules_not_loaded {
	local i
	for i; do
		echo "$marker ${FUNCNAME[0]} $i"
		run syz loaded
		check success
		check output_not_pattern "^$i$"
		via_tty run syz loaded
		check success
		check output_not_pattern "\<$i\>"
		run syz isloaded "$i"
		check success
		check output_exact "$i not loaded"
	done
}

echo "$marker prelim"
check envvar_pattern "SYZ_PATH" '^'"$basedir"'/sw$'
check envvar_unset SYZ_{MODULES,MODULES_ABS,INACTIVE_MODULES}

echo
echo "$marker load"
set -e
. ./syzzle
set +e

check envvar_pattern "SYZ_VERSION" '.'
check envvar_pattern "SYZ_PATH" '^'"$basedir"'/sw$'
check envvar_set SYZ_{MODULES,MODULES_ABS,INACTIVE_MODULES}
check envvar_exact "SYZ_MODULES" ''
check envvar_exact "SYZ_MODULES_ABS" ''
check envvar_exact "SYZ_INACTIVE_MODULES" ''

echo
run syz avail
check success
check output_exact ''
via_tty run syz avail
check success
check output_exact 'No modules available.'

for i in $test_pvs; do
	mkdir -p "$basedir/sw/$i"/{bin,lib}
done

echo
run syz avail
check success
check output_exact "$test_pvs"
via_tty run syz avail
check success
check output_pattern 'Available modules'
check output_pattern $test_pvs

echo
run syz version
check success
check output_pattern "version" "$SYZ_VERSION"

echo
run syz empty
check success
o_empty="$o"
run syz
check success
check output_exact "$o_empty"

echo
run syz show
check success
o_show="$o"
run syz status
check success
check output_exact "$o_show"

echo
check modules_not_loaded 'abc/1.0'
check modules_not_loaded 'def/1.1'
check modules_not_loaded 'ghi/1.2'
check no_modules_loaded
check no_modules_inactive

echo
run syz load abc/1.0
check success
check output_pattern 'Loading' 'abc/1.0'
check envvar_pattern 'SYZ_MODULES' 'abc/1.0'
check envvar_pattern 'SYZ_MODULES_ABS' "$basedir"/sw/abc/1.0
check envvar_pattern 'PATH' "$basedir"/sw/abc/1.0/bin

check modules_loaded 'abc/1.0'
check modules_not_loaded 'def/1.1'
check modules_not_loaded 'ghi/1.2'
check no_modules_inactive

echo
run syz load def/1.1
check success
check output_pattern 'Loading' 'def/1.1'
check envvar_pattern 'SYZ_MODULES' 'def/1.1'
check envvar_pattern 'SYZ_MODULES_ABS' "$basedir"/sw/def/1.1
check envvar_pattern 'PATH' "$basedir"/sw/def/1.1/bin

check modules_loaded 'abc/1.0'
check modules_loaded 'def/1.1'
check modules_not_loaded 'ghi/1.2'
check no_modules_inactive

echo
run syz load ghi/1.2
check success
check output_pattern 'Loading' 'ghi/1.2'
check envvar_pattern 'SYZ_MODULES' 'ghi/1.2'
check envvar_pattern 'SYZ_MODULES_ABS' "$basedir"/sw/ghi/1.2
check envvar_pattern 'PATH' "$basedir"/sw/ghi/1.2/bin

check modules_loaded 'abc/1.0'
check modules_loaded 'def/1.1'
check modules_loaded 'ghi/1.2'
check no_modules_inactive

echo
run syz unload def/1.1
check success
check output_pattern 'Unloading' 'def/1.1'
check envvar_not_pattern 'SYZ_MODULES' 'def/1.1'
check envvar_not_pattern 'SYZ_MODULES_ABS' "$basedir"/sw/def/1.1
check envvar_not_pattern 'PATH' "$basedir"/sw/def/1.1/bin

check modules_loaded 'abc/1.0'
check modules_not_loaded 'def/1.1'
check modules_loaded 'ghi/1.2'
check no_modules_inactive

echo
run syz unload abc/1.0
check success
check output_pattern 'Unloading' 'abc/1.0'
check envvar_not_pattern 'SYZ_MODULES' 'abc/1.0'
check envvar_not_pattern 'SYZ_MODULES_ABS' "$basedir"/sw/abc/1.0
check envvar_not_pattern 'PATH' "$basedir"/sw/abc/1.0/bin

check modules_not_loaded 'abc/1.0'
check modules_not_loaded 'def/1.1'
check modules_loaded 'ghi/1.2'
check no_modules_inactive

echo
run syz unload ghi/1.2
check success
check output_pattern 'Unloading' 'ghi/1.2'
check envvar_not_pattern 'SYZ_MODULES' 'ghi/1.2'
check envvar_not_pattern 'SYZ_MODULES_ABS' "$basedir"/sw/ghi/1.2
check envvar_not_pattern 'PATH' "$basedir"/sw/ghi/1.2/bin

check modules_not_loaded 'abc/1.0'
check modules_not_loaded 'def/1.1'
check modules_not_loaded 'ghi/1.2'
check no_modules_loaded
check no_modules_inactive





